---
- name: running yum update
  yum: name=* state=latest
  environment: proxy_env

- name: Installing rsnapshot
  yum: name=rsnapshot state=installed
  environment: proxy_env

- name: Create a SSH key for 'root'
  user: name=root generate_ssh_key=yes ssh_key_file=.ssh/{{ rsnapshot_ssh_key }}
  when: rsnapshot_ssh_key != False

- name: Get public key from RSNAPSHOT server to ansible server
  fetch: src=/root/.ssh/id_rsa.pub dest=pubic_key 


#updating rsnapshot.conf also includes configuring backup of remote machines
- name: updating rsnapshot.conf
  template: src=rsnapshot.conf.j2 dest=/etc/rsnapshot.conf owner=root group=root mode=644 backup=yes

- name: Configure cron
  cron: name="{{ item.name }}"
        user=root
        cron_file=ansible_rsnapshot
        month={{ item.get('month', '*') }}
        weekday={{ item.get('weekday', '*') }}
        day={{ item.get('day', '*') }}
        hour={{ item.get('hour', '*') }}
        minute={{ item.get('minute', '*') }}
        job="{{ item.get('job', '*') }}"
  with_items: rsnapshot_crontab